dist: bionic

before_install:
  - openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_key
  - ssh-add deploy_key

install:
  - sudo apt update
  - sudo apt install hugo

script:
  - ls
  - hugo

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/public root@51.38.129.95:/var/www/altosterino.com/html
  on:
    branch: master